
import { Item, ItemType, BodyPart, BodyPartCondition, EquipSlot } from '../types';

export const ITEMS_DATA: Record<string, Item> = {
  // Existing Items Updated
  'rusty_sword': {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    description: 'An old, tarnished sword. It has seen better days, but it can still serve a purpose.',
    type: ItemType.WEAPON,
    attackBonus: 2,
    isEquippable: true,
    equipSlot: EquipSlot.MAIN_HAND,
    value: 10,
  },
  'health_potion': {
    id: 'health_potion',
    name: 'Health Potion',
    description: 'A small vial filled with a swirling red liquid. Restores a small amount of overall health.',
    type: ItemType.POTION,
    healAmount: 25, // General health
    isUsable: true,
    value: 25,
  },
  'old_key': {
    id: 'old_key',
    name: 'Old Key',
    description: 'A heavy iron key, clearly very old. It might unlock something important in ancient ruins.',
    type: ItemType.KEY,
    unlocks: 'crypt_door_level1', 
    value: 5,
  },
  'goblin_ear': {
    id: 'goblin_ear',
    name: 'Goblin Ear',
    description: 'A severed goblin ear. Gross, but some people collect these as proof of a kill.',
    type: ItemType.QUEST_ITEM,
    value: 1,
  },
  'leather_armor': {
    id: 'leather_armor',
    name: 'Leather Armor',
    description: 'Simple but sturdy armor made of hardened leather. Protects the torso.',
    type: ItemType.ARMOR,
    defenseBonus: 2,
    isEquippable: true,
    equipSlot: EquipSlot.TORSO,
    value: 40,
  },
  'mystic_orb': {
    id: 'mystic_orb',
    name: 'Mystic Orb',
    description: 'A faintly glowing orb, warm to the touch. It seems to hum with a gentle energy.',
    type: ItemType.QUEST_ITEM, 
    value: 0, 
  },
  'iron_sword': {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A standard sword forged from iron. Reliable and effective.',
    type: ItemType.WEAPON,
    attackBonus: 5,
    isEquippable: true,
    equipSlot: EquipSlot.MAIN_HAND,
    value: 75,
  },
  'dwarven_axe': {
    id: 'dwarven_axe',
    name: 'Dwarven Axe',
    description: 'A masterfully crafted axe of dwarven make, heavy and sharp.',
    type: ItemType.WEAPON,
    attackBonus: 7,
    isEquippable: true,
    equipSlot: EquipSlot.MAIN_HAND,
    value: 150,
  },
  'short_bow': {
    id: 'short_bow',
    name: 'Short Bow',
    description: 'A simple wooden bow, good for hunting or skirmishing.',
    type: ItemType.WEAPON,
    attackBonus: 4, 
    isEquippable: true,
    equipSlot: EquipSlot.MAIN_HAND, // Bows usually take main hand, arrows are conceptual for now
    value: 60,
  },
  'silver_dagger': {
    id: 'silver_dagger',
    name: 'Silver Dagger',
    description: 'A dagger with a gleaming silver blade, said to be effective against unnatural creatures.',
    type: ItemType.WEAPON,
    attackBonus: 3,
    isEquippable: true,
    equipSlot: EquipSlot.MAIN_HAND, // Or OFF_HAND if dual wielding is implemented
    value: 100,
  },
  'studded_leather_armor': {
    id: 'studded_leather_armor',
    name: 'Studded Leather Armor',
    description: 'Leather armor reinforced with metal studs for better protection of the torso.',
    type: ItemType.ARMOR,
    defenseBonus: 4,
    isEquippable: true,
    equipSlot: EquipSlot.TORSO,
    value: 120,
  },
  'iron_helmet': { // Renamed from 'iron_helm' in thought process for consistency
    id: 'iron_helmet', // Changed from iron_helm to iron_helmet
    name: 'Iron Helmet',
    description: 'A sturdy iron helmet offering good protection for the head.',
    type: ItemType.ARMOR, 
    defenseBonus: 2, 
    isEquippable: true, 
    equipSlot: EquipSlot.HEAD,
    value: 60, // Increased value
  },
  'cultist_robes': {
    id: 'cultist_robes',
    name: 'Cultist Robes',
    description: 'Dark, hooded robes worn by shadowy cultists. Offer minimal protection but are unsettling.',
    type: ItemType.ARMOR,
    defenseBonus: 1,
    isEquippable: true,
    equipSlot: EquipSlot.TORSO,
    value: 30,
  },
  'spider_silk_tunic': {
    id: 'spider_silk_tunic',
    name: 'Spider Silk Tunic',
    description: 'A surprisingly strong and light tunic woven from giant spider silk.',
    type: ItemType.ARMOR,
    defenseBonus: 3,
    isEquippable: true,
    equipSlot: EquipSlot.TORSO,
    value: 180,
  },
  'potion_of_strength': {
    id: 'potion_of_strength',
    name: 'Potion of Strength',
    description: 'A bubbling, crimson potion that temporarily boosts your Strength.',
    type: ItemType.POTION,
    isUsable: true,
    statBonus: { stat: 'Strength', amount: 2, duration: 300 },
    value: 75,
  },
  'potion_of_dexterity': {
    id: 'potion_of_dexterity',
    name: 'Potion of Dexterity',
    description: 'A shimmering green liquid that enhances your Dexterity.',
    type: ItemType.POTION,
    isUsable: true,
    statBonus: { stat: 'Dexterity', amount: 2, duration: 300 },
    value: 70,
  },
  'borins_lost_hammer': {
    id: 'borins_lost_hammer',
    name: "Borin's Lost Hammer",
    description: "A finely crafted blacksmith's hammer, clearly a prized possession. Engraved with dwarven runes.",
    type: ItemType.QUEST_ITEM,
    value: 0,
  },
  'shadow_amulet': {
    id: 'shadow_amulet',
    name: 'Shadow Amulet',
    description: 'A dark, obsidian amulet that feels cold to the touch and pulses with a faint, unsettling energy.',
    type: ItemType.QUEST_ITEM,
    equipSlot: EquipSlot.AMULET, // Can be equipped for flavor or future effects
    isEquippable: true,
    value: 0,
  },
  'spider_venom_gland': {
    id: 'spider_venom_gland',
    name: 'Spider Venom Gland',
    description: "A pulsating gland taken from a giant spider, still oozing potent venom. Grizelda might want this.",
    type: ItemType.QUEST_ITEM,
    value: 0,
  },
   'lost_tome_of_eldoria': {
    id: 'lost_tome_of_eldoria',
    name: 'Lost Tome of Eldoria',
    description: 'An ancient, leather-bound book. Its pages are brittle, but it seems to contain forgotten lore.',
    type: ItemType.BOOK, 
    isUsable: false, 
    value: 0, 
  },
  'crude_splint': {
    id: 'crude_splint',
    name: 'Crude Splint',
    description: 'A pair of rough wooden sticks and some cloth. Can be used to temporarily mend a severely injured limb, improving its condition slightly.',
    type: ItemType.TOOL,
    isUsable: true,
    bodyPartHeal: { conditionImprovement: BodyPartCondition.INJURED }, 
    value: 15,
  },
  'goblin_totem': {
    id: 'goblin_totem',
    name: 'Goblin Totem',
    description: 'A crudely carved wooden totem, adorned with feathers and teeth. Radiates a faint, unsettling energy.',
    type: ItemType.QUEST_ITEM, 
    value: 5, 
  },

  // New Shield Items
  'wooden_buckler': {
    id: 'wooden_buckler',
    name: 'Wooden Buckler',
    description: 'A small, round wooden shield. Offers minimal protection.',
    type: ItemType.SHIELD,
    defenseBonus: 1,
    isEquippable: true,
    equipSlot: EquipSlot.OFF_HAND,
    value: 30,
  },
  'iron_kite_shield': {
    id: 'iron_kite_shield',
    name: 'Iron Kite Shield',
    description: 'A sturdy iron shield shaped like a kite. Provides good defense.',
    type: ItemType.SHIELD,
    defenseBonus: 3,
    isEquippable: true,
    equipSlot: EquipSlot.OFF_HAND,
    value: 100,
  },

  // Other New Equipment
  'leather_cap': {
    id: 'leather_cap',
    name: 'Leather Cap',
    description: 'A simple cap made of hardened leather. Better than nothing for your head.',
    type: ItemType.ARMOR,
    defenseBonus: 1,
    isEquippable: true,
    equipSlot: EquipSlot.HEAD,
    value: 20,
  },
  'worn_leather_boots': {
    id: 'worn_leather_boots',
    name: 'Worn Leather Boots',
    description: 'Basic leather boots, showing signs of wear but still functional.',
    type: ItemType.ARMOR,
    defenseBonus: 1,
    isEquippable: true,
    equipSlot: EquipSlot.FEET,
    value: 25,
  },
  'sturdy_iron_boots': {
    id: 'sturdy_iron_boots',
    name: 'Sturdy Iron Boots',
    description: 'Heavy boots reinforced with iron plates. Offers good protection for the feet.',
    type: ItemType.ARMOR,
    defenseBonus: 2,
    isEquippable: true,
    equipSlot: EquipSlot.FEET,
    value: 70,
  },
  'rough_leather_gloves': {
    id: 'rough_leather_gloves',
    name: 'Rough Leather Gloves',
    description: 'Simple gloves made from rough leather, offering minor protection for the hands.',
    type: ItemType.ARMOR,
    defenseBonus: 1,
    isEquippable: true,
    equipSlot: EquipSlot.HANDS,
    value: 15,
  },
  'serpents_eye_amulet_item': {
    id: 'serpents_eye_amulet_item',
    name: "Serpent's Eye Amulet",
    description: "A heavy gold amulet shaped like a coiled serpent, with a large, unsettling green gem for an eye. It feels strangely cold.",
    type: ItemType.QUEST_ITEM,
    value: 0, // Quest items typically have no monetary value for selling
    isEquippable: true, // Can be equipped for flavor or if it had stats
    equipSlot: EquipSlot.AMULET,
  },
};
